version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: nst_redis
    volumes:
      - redis_data:/data
    restart: always

  db:
      image: postgres:15-alpine
      container_name: nst_db
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "127.0.0.1:5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      restart: always

  web:
      build: .
      container_name: nst_web
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000
      ports:
        - "127.0.0.1:8000:8000"
      env_file:
        - .env
      depends_on:
        - redis
        - db
      restart: always

  worker:
      build: .
      container_name: nst_worker
      command: celery -A celery_worker.celery_app worker --loglevel=info
      env_file:
        - .env
      depends_on:
        - redis
        - db
      restart: always

volumes:
  postgres_data:
  redis_data: